AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Default: 'vpc-959fcdf0'
    Description: Select a VPC that allows instances access to the Internet.
  ClusterName:
    Type: String
    Default: 'default'
    Description: The cluster name or ARN to create the service in.
  DesiredCount:
    Type: Number
    Default: '1'
    Description: Number of tasks to schedule in on the cluster.
  ALBListenerArn:
    Type: String
    Default: 'arn:aws:elasticloadbalancing:eu-west-1:075458894664:listener/app/ecs-platform-apis/cf8bbfd635abb1de/ad349854d6fa7b4a'
    Description: The ARN of the ELB listener to register the target group with.
  ECSServiceRole:
    Type: String
    Default: 'ecsServiceRole'
    Description: The ARN or name of the IAM role to assign to the ECS service.
  MinimumDeploymentConfigurationTarget:
    Type: Number
    Default: '50'
    Description: The minimum number of tasks, specified as a percentage of the DesiredCount value
  MaximumDeploymentConfigurationTarget:
    Type: Number
    Default: '200'
    Description: The maximum number of tasks, specified as a percentage of the DesiredCount value
  ECSMonitorImageTag:
    Type: String
    Default: 'latest'
    Description: The tag for the desired logging-api image. e.g v1.0.5

Resources:
  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Ref 'AWS::StackName'
      ContainerDefinitions:
      - Name: ecs-monitor
        Cpu: 0
        MemoryReservation: 100
        Memory: 200
        Essential: true
        Image: !Join [':',['160821142532.dkr.ecr.eu-west-1.amazonaws.com/platform/ecs-monitor', !Ref 'ECSMonitorImageTag']]
        PortMappings:
        - ContainerPort: 1337
        LogConfiguration:
          LogDriver: awslogs
          Options:
            'awslogs-group': 'ecs'
            'awslogs-region': 'eu-west-1'
            'awslogs-stream-prefix': 'ecs-monitor'
  Service:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref ClusterName
      DesiredCount: !Ref DesiredCount
      LoadBalancers:
      - ContainerName: ecs-monitor
        ContainerPort: 1337
        TargetGroupArn: !Ref 'targetgroup'
      Role: !Ref 'ECSServiceRole'
      TaskDefinition: !Ref 'TaskDefinition'
      DeploymentConfiguration:
        MaximumPercent: !Ref 'MaximumDeploymentConfigurationTarget'
        MinimumHealthyPercent: !Ref 'MinimumDeploymentConfigurationTarget'
  ECSALBListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      Actions:
      - Type: forward
        TargetGroupArn: !Ref 'targetgroup'
      Conditions:
      - Field: path-pattern
        Values: [/ecs-monitor*]
      ListenerArn: !Ref 'ALBListenerArn'
      Priority: 2
  targetgroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup 
    Properties:
      HealthCheckIntervalSeconds: 5
      HealthCheckPath: /logging/log
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 3
      HealthyThresholdCount: 2
      Name: !Join ['-', ['ecs-monitor-cf', !Select [4, !Split ['/', !Ref 'ALBListenerArn']]]]
      Port: 80
      Protocol: HTTP
      UnhealthyThresholdCount: 5
      VpcId: !Ref 'VpcId'
      TargetGroupAttributes:
        - Key: deregistration_delay.timeout_seconds
          Value: '10'

Outputs:
  ecsservice:
    Value: !Ref 'Service'
  ecscluster:
    Value: !Ref 'ClusterName'
  taskdef:
    Value: !Ref 'TaskDefinition'